### ISSUE TITLE
Configuration customisation is hard

### ISSUE THREAD

**Issue by jeroenrnl** [technicalguru/docker-mailserver-postfixadmin#11]
Due to the way the configuration is managed (standard `config.inc.php` which includes `config.local.php`), it's hard to make small changed to this configuration, this is amplified by the fact that `config.local.php` is a complete copy of `config.inc.php`, so a change will require including that full configuration again.

**Comment by technicalguru** [comment]
Released with v3.3.13.0

**Comment by technicalguru** [comment]
@jeroenrnl - thank you for contribution :)
