### ISSUE TITLE
Build image error

### ISSUE THREAD

**Issue by Oartihsin** [technicalguru/docker-mailserver-postfixadmin#7]
While building the image it throws  a gcp authentication error
What show be the base layer for the postfixadmin docker image

`Step 1/9 : FROM eu.gcr.io/long-grin-186810/rs-php:7.4.4-apache-2.4.38.0
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
`

**Comment by technicalguru** [comment]
Hi Oartihsin,

please check the develop branch. It is already fixed there. Will release it next weeks to master branch.

**Comment by Oartihsin** [comment]
Ok. That worked. Thanks ralph
Though it gives me a connect access denied for the root user. Postfixadmin to mysql connection
![image](https://user-images.githubusercontent.com/50030014/158098449-f39c671f-1107-4a17-a65c-7481b99838cc.png)

**Comment by technicalguru** [comment]
Did you follow the instructions on configuring the password as in here?: https://github.com/technicalguru/docker-mailserver-postfixadmin#environment-variables - Assume you haven't set the environment variables PFA_DB_*

Also make sure to follow the bootstrap process of Postfix Admin software itself: https://github.com/technicalguru/docker-mailserver-postfixadmin#bootstrap-and-setup

**Comment by Oartihsin** [comment]
Yupp Ralph.
I have created a text file with values filled for each variable you mentioned
And passing the text file as argument while running the container

I also went to public/setup.php
It says 
`    Depends on: SQLite - OK
    (change the database_type to 'sqlite' in config.local.php if you want to use SQLite)
    Error: Can't connect to database
    Please edit the $CONF['database_*'] parameters in config.local.php.

    DEBUG INFORMATION:
    Connect: Access denied for user 'root'@'172.17.0.9' (using password: YES)`


P.S I am using mysql:5.7. So i need to change database_type variable
If yes by what?

**Comment by technicalguru** [comment]
Ah, I think you mistook the config instructions. Environment variables are passed into container via docker e.g. by
```
docker ... -e PFA_DB_USER='myuser' -e PFA_DB_PASS='mypassword' ...
```
Can you paste your container startup and configuration (please erase sensitive information such as usernames, passwords, IP addresses).

**Comment by Oartihsin** [comment]
ok I tried running the adhoc command and now I can see the setup page is successfully loaded
Can I know why did it not take the variables from the variable file

**Comment by technicalguru** [comment]
I am not sure, never tried an env file. Usually work with k8s nowadays. Documentation says it works. Maybe the syntax is not correct in your file.

Regarding password: the PFA setup page asks for this? Check the config var $CONF['password_validation']. It might give you a hint how the password has to look like.

**Comment by Oartihsin** [comment]
Ya I checked that
It says at least 2 digits and at least three characters
I added a password with same criteria. Still error persisits

**Comment by technicalguru** [comment]
Hmm, can you try a password like this: "Acsd34fgh" ? Try to keep the digits together and at least 3 letters together. Perhaps that helps (Never had this issue before with my passwords :-)

**Comment by Oartihsin** [comment]
Still the same. Seems like a new issue. Only few strands of hair left to pull out :(

**Comment by Oartihsin** [comment]
Does setup password need to be have the same criteria as admin password. My setup password only has [a-z]*

**Comment by Oartihsin** [comment]
Oh i got that done. the setup password also needs to have 2 digits at least

**Comment by technicalguru** [comment]
Hey, sorry. I thought I answered your post yesterday but just recognized it was still open in my browser. :D Sorry for that.

Good to hear that you meanwhile were able to resolve the issue. Can I close it then?

**Comment by Oartihsin** [comment]
Ya Ya definitely. Thanks Ralph for your help

**Comment by technicalguru** [comment]
Fixed with latest release
