### ISSUE TITLE
Database update to 79 fails

### ISSUE THREAD

**Issue by pixil98** [technicalguru/docker-mailserver-postfixadmin#9]
I don't think this is actually caused by anything in this repo, but I'm starting here as I found it using this image. On a fresh deployment of postfixadmin I run into problems with setup updating the database to version 79. The issue appears to be the following lines of the public/upgrade.php file. None of the indexes exist and it errors out trying to drop them. I was able to work around the issue by commenting out all four db_query_parsed lines.

```
function upgrade_79_mysql() { # MySQL only
    db_query_parsed(_drop_index('admin', 'username'), true);
    db_query_parsed(_drop_index('alias', 'address'), true);
    db_query_parsed(_drop_index('domain', 'domain'), true);
    db_query_parsed(_drop_index('mailbox', 'username'), true);
}
```

**Comment by technicalguru** [comment]
Please refer this to https://github.com/postfixadmin/postfixadmin as this repo just makes use of the release.

**Comment by technicalguru** [comment]
Nothing to do
